version: "3.8"

services:
  latest:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: python:3.10-slim
        FOOOCUS_VERSION: 2.4.3
    image: latitudesh/fooocus:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - 7860:7860 # fooocus webui
      - 8888:8888 # jupyterlab
    # command: /bin/bash
    # tty: true
    # stdin_open: true